# Site Settings
lang: en
title: Jess Speedie
tagline: #Bulma Clean Theme
email: jspeedie@uvic.ca
description: >-
baseurl: ""
url: "https://jspeedie.com"
permalink: pretty
favicon: assets/images/favicon.png
gh_sponsor: #chrisrhymes
#hide_share_buttons: true
theme_color: '#999999'
fixed_navbar: top
direction: auto #one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/page:num" #"/blog/page:num"




plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "J. Speedie"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: false

markdown: kramdown
highlighter: rouge

# footer_menu: example_footer_menu

collections:
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
